### ISSUE TITLE
Problem with linker... `ld: unknown option: -T`

### ISSUE THREAD

**Issue by nbennett320** [samkravitz/maestro#2]
I'll retry on linux soon to see if that fixes it, I'm pretty sure it will. Just wanted to comment to get that GitHub activity 💪

**Comment by samkravitz** [comment]
Thank you for raising this issue. Per the GNU ld man pages: 
`-T scriptfile
       --script=scriptfile
           Use scriptfile as the linker script.  This script replaces ld's
           default linker script (rather than adding to it), so commandfile must
           specify everything necessary to describe the output file.    If
           scriptfile does not exist in the current directory, "ld" looks for it
           in the directories specified by any preceding -L options.  Multiple -T
           options accumulate.`

Please post your platform and linker version, and I will look into ensuring maestro's build system is as comprehensive and cross platform as possible.

**Comment by nbennett320** [comment]
Oh thanks .. this work'd like a dream
